[build]
  # Directorio de publicación
  publish = "."

[build.environment]
  NODE_VERSION = "18"

# Configuración para Identity
[context.production.environment]
  NETLIFY_USE_YARN = "true"

# Headers para mejorar la seguridad
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Configuración para archivos estáticos
[[headers]]
  for = "/img/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Configuración para el admin
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

# Configuración para el CMS
[[redirects]]
  from = "/noticias/admin/*"
  to = "/noticias/admin/index.html"
  status = 200