backend:
  name: git-gateway
  branch: main

media_folder: "img/noticias"
public_folder: "/img/noticias"

site_url: https://incomparable-puffpuff-56cda0.netlify.app
display_url: https://incomparable-puffpuff-56cda0.netlify.app
logo_url: /img/Logo.jpg

# Configuración de autenticación
publish_mode: editorial_workflow
slug:
  encoding: "ascii"
  clean_accents: true

collections:
  - name: "noticias"
    label: "Noticias"
    folder: "_noticias"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - {
          label: "Fecha",
          name: "date",
          widget: "datetime",
          format: "YYYY-MM-DD HH:mm:ss",
        }
      - {
          label: "Autor",
          name: "author",
          widget: "string",
          default: "TriInfinity",
        }
      - {
          label: "Categoría",
          name: "category",
          widget: "select",
          options:
            [
              { label: "Competiciones", value: "competiciones" },
              { label: "Club", value: "club" },
              { label: "Eventos", value: "eventos" },
              { label: "Entrenamientos", value: "entrenamientos" },
              { label: "Logros", value: "logros" },
            ],
        }
      - { label: "Imagen", name: "image", widget: "image", required: false }
      - {
          label: "Resumen",
          name: "excerpt",
          widget: "text",
          hint: "Breve descripción de la noticia (máx. 200 caracteres)",
        }
      - { label: "Contenido", name: "body", widget: "markdown" }
      - {
          label: "Destacada",
          name: "featured",
          widget: "boolean",
          default: false,
          hint: "Marca esta casilla si quieres que la noticia aparezca destacada",
        }
