backend:
  name: git-gateway
  branch: main

media_folder: "img"
public_folder: "/img"

collections:
  - name: "noticias"
    label: "Noticias"
    folder: "_noticias"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Fecha", name: "date", widget: "datetime"}
      - {label: "Autor", name: "author", widget: "string", default: "TriInfinity"}
      - {label: "Categoría", name: "category", widget: "select", options: ["competiciones", "club", "eventos", "entrenamientos", "logros"]}
      - {label: "Imagen", name: "image", widget: "image", required: false}
      - {label: "Resumen", name: "excerpt", widget: "text"}
      - {label: "Contenido", name: "body", widget: "markdown"}
      - {label: "Destacada", name: "featured", widget: "boolean", default: false}